// ...DOM Basics Learning...

// document;
// document.firstElementChild;
// document.firstElementChild.firstElementChild;
// document.firstElementChild.lastElementChild;
// document.firstElementChild.lastElementChild.firstElementChild;
// var heading = document.firstElementChild.lastElementChild.firstElementChild;
// heading.innerHTML = "Good Bye.";
// heading.style.color = "green";
// document.querySelector("input").click();
// var third = document.firstElementChild.lastElementChild.lastElementChild.lastElementChild;
// third.innerHTML = "Usama";
// document.firstElementChild.lastElementChild.querySelector("ul").lastElementChild.innerHTML = "Usama";
// document.getElementsByTagName("li");
// document.getElementsByTagName("li").style.color = "green"; // Error.
// document.getElementsByTagName("li")[2].style.color = "green";
// document.getElementsByTagName("li").length;
// document.getElementsByClassName("btn");
// document.getElementsByClassName("btn").style.color = "green"; // Error.
// document.getElementsByClassName("btn")[0].style.color = "green";
// document.getElementById("title");
// document.getElementById("title").innerHTML = "Good Bye.";
// document.querySelector("h1");
// document.querySelector("#title");
// document.querySelector(".btn");
// document.querySelector("li a");
// document.querySelector("a");
// document.querySelector("li.item");
// document.querySelector("#list a");
// document.querySelector("#list .item");
// document.querySelectorAll("#list .item");
// document.querySelectorAll("#list .item")[2].style.color = "green";
// document.querySelector("li a").style.color = "red";
// document.querySelector("h1").style.color = "green";
// document.querySelector("h1").style.fontSize = "10rem";
// document.querySelector("h1").style.visibility = "hidden";
// document.querySelector(".btn").style.backgroundColor = "yellow";
// document.querySelector("button").classList.add("invisible");
// document.querySelector("button").classList.remove("invisible");
// document.querySelector("button").classList.toggle("invisible");
// document.querySelector("h1").classList.toggle("huge");
// document.getElementById("title").innerHTML;
// document.getElementById("title").innerHTML = "Good Bye";
// document.getElementById("title").textContent = "Good Bye";
// document.getElementById("title").innerHTML = "<em>Good Bye</em";
// document.querySelector("a");
// document.querySelector("a").attributes;
// document.querySelector("a").getAttribute("href");
// document.querySelector("a").setAttribute("href", "https://www.bing.com");
